apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dapr-customer-service
  name: dapr-customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-customer-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dapr-customer-service
      annotations: 
        dapr.io/enabled: "true"
        dapr.io/app-id: "customer-service"
        dapr.io/app-port: "9000"
        dapr.io/enable-api-logging: "true"
        dapr.io/config: "daprconfig"
    spec:
      containers:
      - image: dapr-customer-service
        name: dapr-customer-service
        imagePullPolicy: IfNotPresent
        resources: {}
status: {}
