apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-05-23T09:41:57Z"
  labels:
    app: dapr-customer-service
  name: dapr-customer-service
  namespace: default
  resourceVersion: "1924126"
  uid: cd88e33d-9300-47e0-8747-81efb94b3654
spec:
  clusterIP: 10.109.175.171
  clusterIPs:
  - 10.109.175.171
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31670
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: dapr-customer-service
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
